@startuml
!include ../clean.skin

title: Virtual Schema Base Library and Concrete Implementation

package exasolvs {
    component query_renderer
    component request_dispatcher
    ' [dsn->req~lua-virtual-schema-adapter-abstraction~1]
    interface "adapter" <<interface>>
    note as interface_note
        Lua interface
        implicitly defined
    end note
    
    adapter .l. interface_note
    
    request_dispatcher -r-> query_renderer
    request_dispatcher .l.> adapter : use
}

'[dsn->req~lua-virtual-schema-adapter-abstraction~1]

package example_vs <<external>> {
    component entry <<external>>
    component "example_vs_adapter" as vs_adapter
    component metadata_reader
    component query_rewriter
    
    vs_adapter -l-> metadata_reader
    vs_adapter -l-> query_rewriter
    
    metadata_reader -[hidden]d- query_rewriter
    entry -d-> vs_adapter : create
}

entry -r-> request_dispatcher : create
vs_adapter -d- adapter

url of entry is [[../sequence/seq_entry.svg]]
url of request_dispatcher is [[../sequence/seq_handle_request.svg]]
@enduml