@startuml
!include ../clean.skin

title Dispatch Request

participant entry <<external>>
participant RequestDispatcher
participant VirtualSchemaAdapter <<external>>
participant log <<external>>
participant cjson <<external>>
activate entry

' [dsn -> req~translating-json-request-to-lua-tables~1 >> impl, utest]
entry --> RequestDispatcher : adapter_call (request : JSON string)
activate RequestDispatcher

RequestDispatcher -> cjson : decode(request : JSON string)
activate cjson
cjson -->> RequestDispatcher : request : table
deactivate cjson

' [dsn ->  req~reading-user-defined-properties~1 >> impl, utest]
create AdapterProperties
RequestDispatcher -> AdapterProperties : create(request)
activate AdapterProperties
AdapterProperties -->> RequestDispatcher : properties
deactivate AdapterProperties

ref over RequestDispatcher, log : **[[seq_initialize_logging.svg initialize logging]]**

RequestDispatcher -> log : debug(request : JSON string)
activate log
deactivate log

RequestDispatcher -> RequestDispatcher : xpcall
activate RequestDispatcher
alt
    ' [dsn -> req~dispatching-create-virtual-schema-requests~1 >> impl, utest]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_create_virtual_schema.svg create_virtual_schema(request, properties)]]
    activate VirtualSchemaAdapter
else
    ' [dsn -> req~dispatching-get-capabilities-requests~1 >> impl, utest]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_get_capabilities.svg get_capabilities(request, properties)]]
else
    ' [dsn -> req~dispatching-set-properties-requests~1 >> impl, utest]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_set_properties.svg set_properties(request, properties)]]
else
    ' [dsn -> req~dispatching-push-down-requests~1 >> impl, utest]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_pushdown.svg push_down(request, properties)]]
else
    ' [dsn -> req~dispatching-refresh-requests~1 >> impl, utest]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_refresh.svg refresh(request, properties)]]
else
    ' [dsn -> req~dispatching-drop-virtual-schema-requests~1 >> impl, utest]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_drop_virtual_schema.svg drop_virtual_schema(request, properties)]]
end
activate VirtualSchemaAdapter
...
VirtualSchemaAdapter -->> RequestDispatcher : response
deactivate VirtualSchemaAdapter
RequestDispatcher -> cjson : encode(request)
activate cjson
cjson -->> RequestDispatcher : request : JSON string
deactivate cjson
RequestDispatcher -> log : debug (response : JSON string)
activate log
deactivate log
deactivate RequestDispatcher

RequestDispatcher -> log : disconnect ()

alt success
    
    ' [dsn -> req~translating-lua-tables-to-json-responses~1 >> impl, utest]
    RequestDispatcher -->> entry : response : JSON string
else error
    <<-- RequestDispatcher : throw (error)
end

deactivate RequestDispatcher

@enduml