@startuml
!include ../clean.skin

title: Drop Virtual Schema

Participant request_dispatcher
Participant vs_adapter

activate request_dispatcher
request_dispatcher -> vs_adapter : drop virtual schema (request)
activate vs_adapter
vs_adapter -->> request_dispatcher
deactivate vs_adapter 
@enduml