@startuml
!include ../clean.skin

title: Set Properties

Participant request_dispatcher
Participant vs_adapter

activate request_dispatcher
request_dispatcher -> vs_adapter : set properties (request)
activate vs_adapter
vs_adapter -->> request_dispatcher
deactivate vs_adapter 
@enduml