@startuml
!include ../clean.skin

title: Refresch Virtual Schema

Participant RequestDispatcher
Participant VirtualSchemaAdapter <<external>>

activate RequestDispatcher
RequestDispatcher -> vs_adapter : refresh (request, table[])
activate vs_adapter
vs_adapter -->> RequestDispatcher : schema metadata, adapter notes
deactivate vs_adapter
@enduml