@startuml
!include ../clean.skin

title Dispatch Request

participant entry <<external>>
participant RequestDispatcher
participant VirtualSchemaAdapter <<external>>
participant log <<external>>
participant cjson <<external>>
activate entry

'[dsn -> req~translating-json-request-to-lua-tables~1]
entry --> RequestDispatcher : adapter_call (request : JSON string)

activate RequestDispatcher

RequestDispatcher -> cjson : decode (request : JSON string)
activate cjson
cjson -->> RequestDispatcher : request
deactivate cjson

ref over RequestDispatcher, log : **[[seq_initialize_logging.svg initialize logging]]**

RequestDispatcher -> log : debug(request : JSON string)
activate log
deactivate log

RequestDispatcher -> RequestDispatcher : xpcall
activate RequestDispatcher
alt
    '[dsn -> req~dispatching-create-schema-requests~1]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_create_virtual_schema.svg create virtual schema (request)]]
    activate VirtualSchemaAdapter
else
    '[dsn -> req~dispatching-adapter-capabilities-requests~1]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_get_capabilities.svg get capabilities (request)]]
else
    '[dsn -> req~dispatching-set-properties-requests~1]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_set_properties.svg set properties (request)]]
else
    '[dsn -> req~dispatching-push-down-requests~1]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_pushdown.svg pushdown (request)]]
else
    '[dsn -> req~dispatching-refresh-requests~1]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_refresh.svg refresh (request)]]
else
    '[dsn -> req~dispatching-drop-schema-requests~1]
    RequestDispatcher -> VirtualSchemaAdapter : [[seq_drop_virtual_schema.svg drop virtual schema(request)]]
end
activate VirtualSchemaAdapter
...
VirtualSchemaAdapter -->> RequestDispatcher : response
deactivate VirtualSchemaAdapter
RequestDispatcher -> cjson : encode (request)
activate cjson
cjson -->> RequestDispatcher : request : JSON string
deactivate cjson
RequestDispatcher -> log : debug(response : JSON string)
activate log
deactivate log
deactivate RequestDispatcher

RequestDispatcher -> log : disconnect ()

alt success
    
    '[dsn -> req~translating-lua-tables-to-json-responses~1]
    RequestDispatcher -->> entry : response : JSON string
else error
    <<-- RequestDispatcher : throw (error)
end

deactivate RequestDispatcher

@enduml