
@startuml
!include ../clean.skin

title: Get Capabilities

Participant request_dispatcher
Participant vs_adapter

activate request_dispatcher
request_dispatcher -> vs_adapter : get capabilities (request)
activate vs_adapter
'[dsn -> req~excluding-capabilities~1 >> impl, utest]
vs_adapter -> vs_adapter : subtract excluded capabilities()
activate vs_adapter
deactivate vs_adapter
vs_adapter -->> request_dispatcher : capability[]
deactivate vs_adapter 
@enduml