name: CI Build

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        lua_version: [ 5.4 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.8.0"
      - name: Install Lua dependencies
        run: |
          luarocks make --local
      - name: Run tests
        run: |
          busted --coverage
      - name: Run static code analysis
        # Ignore:
        # - 212: unused argument self
        run: |
          luacheck src --codes --ignore 212
      - name: Create report
        run: |
          luacov -c .coverage_config.lua luacov.stats.out
          mkdir -p target
          mv luacov.*.out target/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: luacov-report
          path: target/luacov-reports/*