name: CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt install lua5.4 liblua5.4-dev luarocks
          sudo luarocks config lua_version 5.4
          luarocks build --local --deps-only virtual-schema-common-lua-0.1.0-1.rockspec
      - name: Run tests
        run: |
          busted