name: Publish API documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install Lua and LuaRocks
        run: sudo apt-get install lua luarocks
      - name: Generate API documentation
        run: |
          ./tools/build_docs.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./target/luals-doc

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
